# Build
# -------------------------------------

language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"

# Deployment
# -------------------------------------

deploy:
  provider: npm
  on:
    tags: true
    node: "11"
  api_key:
    secure: "l/Ha+wXgf3WrqNTg1ciA9D+dQOhtM0IOH/dC/Ci06NOK5nFhF4VKEiO9ITKKKT1nH4Q42VjO7koSspMLSzDCM6YldM8nw3Qracj/Rb/IGJ5LFGREWxp5hS4tEvSJHX6BZYikdn7ynO+q6ixedQx6X4FavSm1qudo9hKNDIX4w9v4hyvzpWSLg61LKHCAQJv7+DBJPvfNNZ9OzSUt+TOMvinN4qoDjm3JZzF7+QoJnAoMS2CQ5rshUVXV1OJ9eY8mGvAgdifDloGQczQ7kvu/Mz0cLhjmRj93lcTVF5eRo2YS2QPF7+OMfXsj1vWhAkvtXlTy/gC+oF+TTusMdvvoDHVE2LdMlGCPVEMN/y154pFG0nXf9cih4rb28Hi8ybUxs1BNQY17ejWQndEdoqcLSj+bfI0D0bfAu4aBvhfTmeM9dqThGQaV4i1iBcxSQxdWbM8oB8SqbY38YnDjanCnmwN++6+2rlYKkyRiemAGjpmEsQat51PlHJK0VSP8LxjQrheem7dj8gk98uzSISpio4vFtpgBCYF3EzqJwgRqlGHOB6RAKhxj2NViHhY7PeodnFljXJ9c0oJzURwFcg68AXI5nVOplUYsKNoyllFQmbQwpADV4suKmu3wCwR7FodnzCwPQrfjwfkvOubd8XS56pOOUC7JdXTMSDVnZgQqtoY="
  email: "lsphillips.mail@gmail.com"
