# Build
# -------------------------------------

language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"

# Deployment
# -------------------------------------

deploy:
  provider: npm
  on:
    tags: true
    node: "11"
  api_key:
    secure: ""
  email: "lsphillips.mail@gmail.com"
