name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-and-test:

    strategy:
      matrix:
        node:
          - '12'
          - '14'
          - '16'

    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install NodeJS
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

    runs-on: ubuntu-latest
